### ISSUE TITLE
MSBuild: Unexpected CopyLocal flag

### ISSUE THREAD

**Issue by chris-sung** [akkadotnet/Akka.MultiNodeTestRunner#65]
Hey guys,
I'm getting the following error at running MSBuild @ vs2019

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): error MSB4018: The "ResolveAssemblyReference" task failed unexpectedly.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): error MSB4018: Microsoft.Build.Shared.InternalErrorException: MSB0001: Internal MSBuild Error: Unexpected CopyLocal flag.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): error MSB4018:    at Microsoft.Build.Tasks.CopyLocalStateUtility.IsCopyLocal(CopyLocalState state)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.LogResults(ReferenceTable dependencyTable, List`1 idealAssemblyRemappings, List`1 idealAssemblyRemappingsIdentities, List`1 generalResolutionExceptions)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute(FileExists fileExists, DirectoryExists directoryExists, GetDirectories getDirectories, GetAssemblyName getAssemblyName, GetAssemblyMetadata getAssemblyMetadata, GetRegistrySubKeyNames getRegistrySubKeyNames, GetRegistrySubKeyDefaultValue getRegistrySubKeyDefaultValue, GetLastWriteTime getLastWriteTime, GetAssemblyRuntimeVersion getRuntimeVersion, OpenBaseKey openBaseKey, GetAssemblyPathInGac getAssemblyPathInGac, IsWinMDFile isWinMDFile, ReadMachineTypeFromPEHeader readMachineTypeFromPEHeader)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): error MSB4018:    at Microsoft.Build.Tasks.ResolveAssemblyReference.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2182,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

Packages referenced via NuGet
```
    <PackageReference Include="Akka.Cluster.TestKit" Version="1.4.18" />
    <PackageReference Include="Akka.MultiNodeTestRunner" Version="1.4.18"/>
    <PackageReference Include="Akka.TestKit.Xunit2" Version="1.4.18" />
```

and I was able to workaround the problem via adding IncludeAssets and PrivateAssets in .csproj 
```
    <PackageReference Include="Akka.Cluster.TestKit" Version="1.4.18" />
    <PackageReference Include="Akka.MultiNodeTestRunner" Version="1.4.18">
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	    <PrivateAssets>all</PrivateAssets>
    </PackageReference>    
    <PackageReference Include="Akka.TestKit.Xunit2" Version="1.4.18" />
```

**Comment by IgorFedchenko** [comment]
Hello @chris-sung ,

This repo is kind of draft of new version of MNTR, which will be installed as a test runner nuget package (like xunit or nunit). It will be possible to reference nuget package and run it with `dotnet test` command, or even from Visual Studio UI.

But for the time been, this version of MNTR is not released anywhere. So you need to open you issue here: https://github.com/akkadotnet/akka.net/issues, where the actual `Akka.MultiNodeTestRunner` package implementation is located right now. 
Probably you should not reference this package in your project, but just download it and get `Akka.MultiNodeTestRunner.exe` and use in as a standalone tool as described here: https://getakka.net/articles/networking/multi-node-test-kit.html#running-multinode-specs

**Comment by IgorFedchenko** [comment]
I will close this here since it is not related to this repository. Sorry for confusion.
